### ISSUE TITLE
add the program to F-droid repos

### ISSUE THREAD

**Issue by moshpirit** [deadlyjack/code-editor#94]
Hi! I saw that your wonderful app isn't on [F-droid](http://https://f-droid.org), would you consider adding it there?

[Here's more info about the submit](https://f-droid.org/en/contribute/)

**Comment by deadlyjack** [comment]
Sure I'll do it. Thanks for the suggestion.

**Comment by proletarius101** [comment]
@deadlyjack Hi, to have listing on F-droid, you need to git tag this repo. I can do other things for you ;)

**Comment by proletarius101** [comment]
And is it intended to execute `cordova platform add android` at build time? If you can create the `platform` dir beforehand (in the git repo), it will be easier to be built in F-droid

**Comment by linsui** [comment]
I opened an [MR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8598).

Could you please add fastlane here? Thanks!

The autoupdate doesn't work for now because the tag and the version name mismatch (1.2.43/1.2.143). Could you please fix it in the next release?

**Comment by IzzySoft** [comment]
Congrats – Acode is now [available on F-Droid](https://f-droid.org/packages/com.foxdebug.acode/), so this issue can be closed as solved! So if you don't mind, I'd remove it [from my repo](https://apt.izzysoft.de/fdroid/index/apk/com.foxdebug.acode) again in a few days (where it was listed since 2020-08-05), @deadlyjack? If you need some background for your decision, you [can find it here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ).

**Comment by moshpirit** [comment]
Great!! I'm closing this issue then! :D

**Comment by IzzySoft** [comment]
Yupp! And I take that as confirmation for the "standard procedure" of removal from my repo in (let me check) 2..3 days from now? Should the need arise, it can always be re-listed, you just need to "ring ma bell" :wink:
